import type { ChecklistPhase, PrestaType } from '@/types/project-v2'

export type TemplateTask = { phase: ChecklistPhase; title: string }

export const TEMPLATES: Record<PrestaType, TemplateTask[]> = {
  web: [
    { phase: 'onboarding',     title: 'Réunion de lancement' },
    { phase: 'onboarding',     title: 'Collecte des accès' },
    { phase: 'onboarding',     title: 'Validation du brief' },
    { phase: 'conception',     title: 'Maquettes wireframes' },
    { phase: 'conception',     title: 'Maquettes graphiques' },
    { phase: 'conception',     title: 'Validation design client' },
    { phase: 'developpement',  title: 'Intégration HTML/CSS' },
    { phase: 'developpement',  title: 'Développement fonctionnalités' },
    { phase: 'developpement',  title: 'Mise en place CMS' },
    { phase: 'developpement',  title: 'Tests internes' },
    { phase: 'recette',        title: 'Tests utilisateurs' },
    { phase: 'recette',        title: 'Corrections retours client' },
    { phase: 'recette',        title: 'Validation finale' },
    { phase: 'post_livraison', title: 'Mise en ligne' },
    { phase: 'post_livraison', title: 'Formation client' },
    { phase: 'post_livraison', title: 'Garantie 30j' },
  ],
  seo: [
    { phase: 'onboarding',     title: 'Audit technique SEO' },
    { phase: 'onboarding',     title: 'Accès GA/GSC/Search Console' },
    { phase: 'onboarding',     title: 'Réunion stratégie' },
    { phase: 'conception',     title: 'Analyse mots-clés' },
    { phase: 'conception',     title: 'Stratégie de contenu' },
    { phase: 'conception',     title: 'Audit concurrentiel' },
    { phase: 'developpement',  title: 'Optimisations on-page' },
    { phase: 'developpement',  title: 'Création/optimisation contenu' },
    { phase: 'developpement',  title: 'Stratégie netlinking' },
    { phase: 'recette',        title: 'Rapport de performance' },
    { phase: 'recette',        title: 'Validation objectifs KPI' },
    { phase: 'post_livraison', title: 'Suivi mensuel KPIs' },
    { phase: 'post_livraison', title: 'Rapport final' },
  ],
  erp: [
    { phase: 'onboarding',     title: 'Analyse des processus métier' },
    { phase: 'onboarding',     title: 'Cartographie fonctionnelle' },
    { phase: 'onboarding',     title: 'Réunion cadrage' },
    { phase: 'conception',     title: 'Architecture des modules' },
    { phase: 'conception',     title: 'Paramétrage système' },
    { phase: 'developpement',  title: 'Développement personnalisations' },
    { phase: 'developpement',  title: 'Migration des données' },
    { phase: 'developpement',  title: 'Tests unitaires' },
    { phase: 'recette',        title: 'Formation des équipes' },
    { phase: 'recette',        title: 'Recette fonctionnelle' },
    { phase: 'recette',        title: 'Corrections' },
    { phase: 'post_livraison', title: 'Go-live' },
    { phase: 'post_livraison', title: 'Support post-déploiement J+30' },
  ],
  saas: [
    { phase: 'onboarding',     title: 'Discovery & product roadmap' },
    { phase: 'onboarding',     title: 'Architecture technique' },
    { phase: 'onboarding',     title: 'Setup environnements' },
    { phase: 'conception',     title: 'Maquettes UI/UX' },
    { phase: 'conception',     title: 'Spécifications fonctionnelles' },
    { phase: 'developpement',  title: 'MVP développement' },
    { phase: 'developpement',  title: 'Tests automatisés' },
    { phase: 'developpement',  title: 'CI/CD pipeline' },
    { phase: 'recette',        title: 'Beta testing' },
    { phase: 'recette',        title: 'Corrections et optimisations' },
    { phase: 'post_livraison', title: 'Lancement production' },
    { phase: 'post_livraison', title: 'Monitoring & analytics' },
  ],
  site_web: [
    { phase: 'onboarding',     title: 'Réunion de lancement' },
    { phase: 'onboarding',     title: 'Collecte des accès' },
    { phase: 'onboarding',     title: 'Validation du brief' },
    { phase: 'conception',     title: 'Maquettes wireframes' },
    { phase: 'conception',     title: 'Maquettes graphiques' },
    { phase: 'conception',     title: 'Validation design client' },
    { phase: 'developpement',  title: 'Intégration HTML/CSS' },
    { phase: 'developpement',  title: 'Développement fonctionnalités' },
    { phase: 'recette',        title: 'Tests utilisateurs' },
    { phase: 'recette',        title: 'Corrections retours client' },
    { phase: 'post_livraison', title: 'Mise en ligne' },
    { phase: 'post_livraison', title: 'Formation client' },
  ],
  erp_v2: [
    { phase: 'onboarding',     title: 'Analyse des besoins' },
    { phase: 'onboarding',     title: 'Cartographie fonctionnelle' },
    { phase: 'conception',     title: 'Architecture des modules' },
    { phase: 'developpement',  title: 'Développement personnalisations' },
    { phase: 'developpement',  title: 'Migration des données' },
    { phase: 'recette',        title: 'Recette fonctionnelle' },
    { phase: 'recette',        title: 'Formation des équipes' },
    { phase: 'post_livraison', title: 'Go-live' },
    { phase: 'post_livraison', title: 'Support post-déploiement J+30' },
  ],
  communication: [
    { phase: 'onboarding',     title: 'Brief créatif' },
    { phase: 'onboarding',     title: 'Définition des plateformes cibles' },
    { phase: 'conception',     title: 'Charte éditoriale' },
    { phase: 'conception',     title: 'Calendrier éditorial' },
    { phase: 'developpement',  title: 'Production des contenus' },
    { phase: 'recette',        title: 'Validation client' },
    { phase: 'post_livraison', title: 'Publication et suivi' },
  ],
}
